# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_atendimento.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaAtendimento(object):
    def setupUi(self, TelaAtendimento):
        TelaAtendimento.setObjectName("TelaAtendimento")
        TelaAtendimento.setEnabled(True)
        TelaAtendimento.resize(570, 500)
        TelaAtendimento.setMinimumSize(QtCore.QSize(570, 500))
        TelaAtendimento.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaAtendimento.setFont(font)
        TelaAtendimento.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaAtendimento.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaAtendimento)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(120, 30, 400, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_tipoAten = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tipoAten.setGeometry(QtCore.QRect(40, 110, 151, 20))
        self.lineEdit_tipoAten.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_tipoAten.setPlaceholderText("Informe o atendimento")
        self.lineEdit_tipoAten.setText("")
        self.lineEdit_tipoAten.setCursorPosition(0)
        self.lineEdit_tipoAten.setObjectName("lineEdit_tipoAten")
        self.lineEdit_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data.setGeometry(QtCore.QRect(210, 110, 151, 20))
        self.lineEdit_data.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_data.setText("")
        self.lineEdit_data.setInputMask("00/00/0000;_")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_salvar.setFlat(False)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(360, 220, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 220, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.label_data = QtWidgets.QLabel(self.centralwidget)
        self.label_data.setGeometry(QtCore.QRect(210, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_data.setFont(font)
        self.label_data.setObjectName("label_data")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(380, 85, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.label_ID_medico = QtWidgets.QLabel(self.centralwidget)
        self.label_ID_medico.setGeometry(QtCore.QRect(40, 140, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ID_medico.setFont(font)
        self.label_ID_medico.setObjectName("label_ID_medico")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(True)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 220, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setPlaceholderText("Digite o ID")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setCursorPosition(0)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id_enfer = QtWidgets.QLabel(self.centralwidget)
        self.label_id_enfer.setGeometry(QtCore.QRect(40, 200, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_enfer.setFont(font)
        self.label_id_enfer.setObjectName("label_id_enfer")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 260, 491, 191))
        self.tableWidget.setStyleSheet("""
QTableWidget {
    background-color: #F5F5F5;
    alternate-background-color: #E0FFFF;
}
QHeaderView::section {
    background-color: #504B4B;
    color: white;
    font-weight: bold;
}
""")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.comboBox_status = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_status.setGeometry(QtCore.QRect(380, 110, 151, 21))
        # força usar QListView como view para o popup (mais controle no Windows)
        view = QtWidgets.QListView(self.comboBox_status)
        self.comboBox_status.setView(view)

        # stylesheet só para o campo fechado (opcional)
        self.comboBox_status.setStyleSheet("""
            QComboBox {
                background: transparent;
                border: 1px solid #AAAAAA;
                border-radius: 4px;
                padding-left: 6px;
                color: #333;
            }
        """)

        # stylesheet e atributos para o popup (QListView)
        view.setStyleSheet("""
            QListView {
                background-color: #FFFFFF;
                color: #000000;
                outline: 0;
            }
            QListView::item {
                background-color: #FFFFFF;
                color: #000000;
            }
            QListView::item:selected {
                background-color: #5599ff;
                color: #ffffff;
            }
        """)
        view.setAttribute(QtCore.Qt.WA_StyledBackground, True)

        # garantir paleta (fallback caso o QSS seja ignorado)
        pal = view.palette()
        pal.setColor(QtGui.QPalette.Base, QtGui.QColor("#FFFFFF"))
        pal.setColor(QtGui.QPalette.Text, QtGui.QColor("#000000"))
        pal.setColor(QtGui.QPalette.Highlight, QtGui.QColor("#5599ff"))
        pal.setColor(QtGui.QPalette.HighlightedText, QtGui.QColor("#FFFFFF"))
        view.setPalette(pal)
        # --- fim combo ---
        self.label_qntd_medicos = QtWidgets.QLabel(self.centralwidget)
        self.label_qntd_medicos.setGeometry(QtCore.QRect(320, 140, 90, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_qntd_medicos.setFont(font)
        self.label_qntd_medicos.setObjectName("qntd_medicos")
        self.lineEdit_qtd_medicos = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_qtd_medicos.setGeometry(QtCore.QRect(320, 160, 71, 20))
        self.lineEdit_qtd_medicos.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;")
        self.lineEdit_qtd_medicos.setReadOnly(True)
        self.lineEdit_qtd_medicos.setObjectName("lineEdit_qtd_medicos")
        self.lineEdit_qtd_medicos.setText("")  # valor inicial
        self.label_qntd_enfermeiros = QtWidgets.QLabel(self.centralwidget)
        self.label_qntd_enfermeiros.setGeometry(QtCore.QRect(430, 140, 120, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_qntd_enfermeiros.setFont(font)
        self.label_qntd_enfermeiros.setObjectName("qntd_enfermeiros")
        self.lineEdit_qtd_enfermeiros = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_qtd_enfermeiros.setGeometry(QtCore.QRect(430, 160, 71, 20))
        self.lineEdit_qtd_enfermeiros.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;")
        self.lineEdit_qtd_enfermeiros.setReadOnly(True)
        self.lineEdit_qtd_enfermeiros.setObjectName("lineEdit_qtd_enfermeiros")
        self.lineEdit_qtd_enfermeiros.setText("")  # valor inicial
        self.comboBox_status.setObjectName("comboBox_status")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.label_ID_enfermeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_ID_enfermeiro.setGeometry(QtCore.QRect(130, 140, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ID_enfermeiro.setFont(font)
        self.label_ID_enfermeiro.setObjectName("label_ID_enfermeiro")
        self.label_ID_pacien = QtWidgets.QLabel(self.centralwidget)
        self.label_ID_pacien.setGeometry(QtCore.QRect(220, 140, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ID_pacien.setFont(font)
        self.label_ID_pacien.setObjectName("label_ID_pacien")
        self.lineEdit_id_medico = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_medico.setEnabled(True)
        self.lineEdit_id_medico.setGeometry(QtCore.QRect(40, 160, 71, 20))
        self.lineEdit_id_medico.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_medico.setPlaceholderText("Digite o ID médico")
        self.lineEdit_id_medico.setText("")
        self.lineEdit_id_medico.setObjectName("lineEdit_id_medico")
        self.lineEdit_id_enferm = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_enferm.setEnabled(True)
        self.lineEdit_id_enferm.setGeometry(QtCore.QRect(130, 160, 71, 20))
        self.lineEdit_id_enferm.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_enferm.setPlaceholderText("Digite o ID enfermeiro")
        self.lineEdit_id_enferm.setText("")
        self.lineEdit_id_enferm.setObjectName("lineEdit_id_enferm")
        self.lineEdit_id_pacien = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_pacien.setEnabled(True)
        self.lineEdit_id_pacien.setGeometry(QtCore.QRect(220, 160, 71, 20))
        self.lineEdit_id_pacien.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_pacien.setPlaceholderText("Digite o ID paciente")
        self.lineEdit_id_pacien.setText("")
        self.lineEdit_id_pacien.setObjectName("lineEdit_id_pacien")
        TelaAtendimento.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaAtendimento)
        self.statusbar.setObjectName("statusbar")
        TelaAtendimento.setStatusBar(self.statusbar)
        TelaAtendimento.setWindowIcon(QtGui.QIcon("hospital.png"))
        self.retranslateUi(TelaAtendimento)
        QtCore.QMetaObject.connectSlotsByName(TelaAtendimento)

    def retranslateUi(self, TelaAtendimento):
        _translate = QtCore.QCoreApplication.translate
        TelaAtendimento.setWindowTitle(_translate("TelaAtendimento", "Sistema Hospitalar"))
        self.Label_titulo.setText(_translate("TelaAtendimento", "Informações do Atendimento"))
        self.pushButton_salvar.setText(_translate("TelaAtendimento", "Salvar"))
        self.pushButtor_visu.setText(_translate("TelaAtendimento", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaAtendimento", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaAtendimento", "Excluir"))
        self.label_nome.setText(_translate("TelaAtendimento", "Tipo de atendimento:"))
        self.label_data.setText(_translate("TelaAtendimento", "Data:"))
        self.label_status.setText(_translate("TelaAtendimento", "Status"))
        self.label_ID_medico.setText(_translate("TelaAtendimento", "ID Médico:"))
        self.label_qntd_medicos.setText(_translate("TelaAtendimento", "Médicos ativos:"))
        self.label_qntd_enfermeiros.setText(_translate("TelaAtendimento", "Enfs. ativos:"))
        
        self.label_id_enfer.setText(_translate("TelaAtendimento", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaAtendimento", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaAtendimento", "Tipo de Atend.:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaAtendimento", "Data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaAtendimento", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaAtendimento", "Médico"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaAtendimento", "Enfermeiro"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaAtendimento", "Paciente"))
        self.comboBox_status.setItemText(0, _translate("TelaAtendimento", "Aberto"))
        self.comboBox_status.setItemText(1, _translate("TelaAtendimento", "Concluído"))
        self.comboBox_status.setItemText(2, _translate("TelaAtendimento", "Cancelado"))
        self.label_ID_enfermeiro.setText(_translate("TelaAtendimento", "ID Enfer.:"))
        self.label_ID_pacien.setText(_translate("TelaAtendimento", "ID Paciente:"))
        self.tableWidget.setColumnWidth(0,10)
        self.tableWidget.setColumnWidth(1,100)
        self.tableWidget.setColumnWidth(5,85)
        self.tableWidget.setColumnWidth(6,67)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaAtendimento = QtWidgets.QMainWindow()
    ui = Ui_TelaAtendimento()
    ui.setupUi(TelaAtendimento)
    TelaAtendimento.show()
    sys.exit(app.exec_())
