# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaMenu2(object):
    def setupUi(self, TelaMenu2):
        TelaMenu2.setObjectName("TelaMenu2")
        TelaMenu2.setEnabled(True)
        TelaMenu2.resize(570, 500)
        TelaMenu2.setMinimumSize(QtCore.QSize(570, 500))
        TelaMenu2.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaMenu2.setFont(font)
        TelaMenu2.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaMenu2.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaMenu2)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(190, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.pushButton_cidade = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cidade.setGeometry(QtCore.QRect(170, 220, 221, 31))
        self.pushButton_cidade.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_cidade.setFlat(False)
        self.pushButton_cidade.setObjectName("pushButton_cidade")
        self.pushButtor_Tutrno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_Tutrno.setGeometry(QtCore.QRect(170, 140, 221, 31))
        self.pushButtor_Tutrno.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_Tutrno.setFlat(False)
        self.pushButtor_Tutrno.setObjectName("pushButtor_Tutrno")
        self.pushButton_estado = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_estado.setGeometry(QtCore.QRect(170, 180, 221, 31))
        self.pushButton_estado.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_estado.setFlat(False)
        self.pushButton_estado.setObjectName("pushButton_estado")
        self.pushButtor_pagAnterior = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_pagAnterior.setGeometry(QtCore.QRect(40, 400, 101, 31))
        self.pushButtor_pagAnterior.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_pagAnterior.setFlat(False)
        self.pushButtor_pagAnterior.setObjectName("pushButtor_pagAnterior")
        TelaMenu2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaMenu2)
        self.statusbar.setObjectName("statusbar")
        TelaMenu2.setStatusBar(self.statusbar)

        self.retranslateUi(TelaMenu2)
        QtCore.QMetaObject.connectSlotsByName(TelaMenu2)

    def retranslateUi(self, TelaMenu2):
        _translate = QtCore.QCoreApplication.translate
        TelaMenu2.setWindowTitle(_translate("TelaMenu2", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaMenu2", "Menu Hospital"))
        self.pushButton_cidade.setText(_translate("TelaMenu2", "Cidade"))
        self.pushButtor_Tutrno.setText(_translate("TelaMenu2", "Turno"))
        self.pushButton_estado.setText(_translate("TelaMenu2", "Estado"))
        self.pushButtor_pagAnterior.setText(_translate("TelaMenu2", "Página anterior"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMenu2 = QtWidgets.QMainWindow()
    ui = Ui_TelaMenu2()
    ui.setupUi(TelaMenu2)
    TelaMenu2.show()
    sys.exit(app.exec_())
