# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_leito.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaAtendimento(object):
    def setupUi(self, TelaAtendimento):
        TelaAtendimento.setObjectName("TelaAtendimento")
        TelaAtendimento.setEnabled(True)
        TelaAtendimento.resize(570, 500)
        TelaAtendimento.setMinimumSize(QtCore.QSize(570, 500))
        TelaAtendimento.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        TelaAtendimento.setFont(font)
        TelaAtendimento.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaAtendimento.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaAtendimento)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(160, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_tipoLeito = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tipoLeito.setGeometry(QtCore.QRect(40, 110, 271, 20))
        self.lineEdit_tipoLeito.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_tipoLeito.setText("")
        self.lineEdit_tipoLeito.setCursorPosition(0)
        self.lineEdit_tipoLeito.setObjectName("lineEdit_tipoLeito")
        self.lineEdit_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data.setGeometry(QtCore.QRect(340, 170, 101, 20))
        self.lineEdit_data.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_data.setText("")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_salvar.setFlat(False)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(360, 220, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 220, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.label_capacidade = QtWidgets.QLabel(self.centralwidget)
        self.label_capacidade.setGeometry(QtCore.QRect(340, 140, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_capacidade.setFont(font)
        self.label_capacidade.setObjectName("label_capacidade")
        self.lineEdit_id_leito = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_leito.setEnabled(False)
        self.lineEdit_id_leito.setGeometry(QtCore.QRect(40, 220, 71, 20))
        self.lineEdit_id_leito.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_leito.setText("")
        self.lineEdit_id_leito.setObjectName("lineEdit_id_leito")
        self.label_id_leito = QtWidgets.QLabel(self.centralwidget)
        self.label_id_leito.setGeometry(QtCore.QRect(40, 200, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_leito.setFont(font)
        self.label_id_leito.setObjectName("label_id_leito")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 260, 491, 191))
        self.tableWidget.setStyleSheet("\n"
"color:#333;\n"
"background: transparent; \n"
"border-radius: 6px; \n"
"border: 1px solid #AAAAAA;  \n"
"ColumnWidth:1")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.lineEdit_tipoNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tipoNum.setGeometry(QtCore.QRect(40, 170, 101, 20))
        self.lineEdit_tipoNum.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_tipoNum.setText("")
        self.lineEdit_tipoNum.setCursorPosition(0)
        self.lineEdit_tipoNum.setObjectName("lineEdit_tipoNum")
        self.label_numero = QtWidgets.QLabel(self.centralwidget)
        self.label_numero.setGeometry(QtCore.QRect(40, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_numero.setFont(font)
        self.label_numero.setObjectName("label_numero")
        self.label_id_setor = QtWidgets.QLabel(self.centralwidget)
        self.label_id_setor.setGeometry(QtCore.QRect(340, 80, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_setor.setFont(font)
        self.label_id_setor.setObjectName("label_id_setor")
        self.lineEdit_tipoCap = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tipoCap.setGeometry(QtCore.QRect(340, 110, 71, 20))
        self.lineEdit_tipoCap.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_tipoCap.setText("")
        self.lineEdit_tipoCap.setCursorPosition(0)
        self.lineEdit_tipoCap.setObjectName("lineEdit_tipoCap")
        TelaAtendimento.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaAtendimento)
        self.statusbar.setObjectName("statusbar")
        TelaAtendimento.setStatusBar(self.statusbar)

        self.retranslateUi(TelaAtendimento)
        QtCore.QMetaObject.connectSlotsByName(TelaAtendimento)

    def retranslateUi(self, TelaAtendimento):
        _translate = QtCore.QCoreApplication.translate
        TelaAtendimento.setWindowTitle(_translate("TelaAtendimento", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaAtendimento", "Leito"))
        self.pushButton_salvar.setText(_translate("TelaAtendimento", "Salvar"))
        self.pushButtor_visu.setText(_translate("TelaAtendimento", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaAtendimento", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaAtendimento", "Excluir"))
        self.label_nome.setText(_translate("TelaAtendimento", "Tipo:"))
        self.label_capacidade.setText(_translate("TelaAtendimento", "Capacidade:"))
        self.label_id_leito.setText(_translate("TelaAtendimento", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaAtendimento", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaAtendimento", "Tipo de Atend.:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaAtendimento", "Data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaAtendimento", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaAtendimento", "Médico"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaAtendimento", "Enfermeiro"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaAtendimento", "Paciente"))
        self.label_numero.setText(_translate("TelaAtendimento", "Numero:"))
        self.label_id_setor.setText(_translate("TelaAtendimento", "ID Setor:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaAtendimento = QtWidgets.QMainWindow()
    ui = Ui_TelaAtendimento()
    ui.setupUi(TelaAtendimento)
    TelaAtendimento.show()
    sys.exit(app.exec_())
