# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_medico.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaMedico(object):
    def setupUi(self, TelaMedico):
        TelaMedico.setObjectName("TelaMedico")
        TelaMedico.setEnabled(True)
        TelaMedico.resize(570, 500)
        TelaMedico.setMinimumSize(QtCore.QSize(570, 500))
        TelaMedico.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaMedico.setFont(font)
        TelaMedico.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaMedico.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaMedico)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(140, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(40, 110, 311, 20))
        self.lineEdit_nome.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_nome.setPlaceholderText("Digite o nome")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setCursorPosition(0)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_crm = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_crm.setGeometry(QtCore.QRect(380, 110, 151, 20))
        self.lineEdit_crm.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_crm.setText("")
        self.lineEdit_crm.setPlaceholderText("Digite o CRM")
        self.lineEdit_crm.setObjectName("lineEdit_crm")
        self.lineEdit_especialidade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_especialidade.setGeometry(QtCore.QRect(40, 170, 311, 21))
        self.lineEdit_especialidade.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_especialidade.setText("")
        self.lineEdit_especialidade.setPlaceholderText("Digite a especialidade")
        self.lineEdit_especialidade.setObjectName("lineEdit_especialidade")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(460, 270, 75, 23))
        self.pushButton_cadastrar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_cadastrar.setFlat(False)
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(460, 300, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(460, 330, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(460, 360, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.label_crm = QtWidgets.QLabel(self.centralwidget)
        self.label_crm.setGeometry(QtCore.QRect(380, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_crm.setFont(font)
        self.label_crm.setObjectName("label_crm")
        self.label_especialidade = QtWidgets.QLabel(self.centralwidget)
        self.label_especialidade.setGeometry(QtCore.QRect(40, 150, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_especialidade.setFont(font)
        self.label_especialidade.setObjectName("label_especialidade")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(False)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 230, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setPlaceholderText("Digite o ID")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(40, 210, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 270, 391, 181))
        self.tableWidget.setStyleSheet("""
QTableWidget {
    background-color: #F5F5F5;
    alternate-background-color: #E0FFFF;
}
QHeaderView::section {
    background-color: #504B4B;
    color: white;
    font-weight: bold;
}
""")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        TelaMedico.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaMedico)
        self.statusbar.setObjectName("statusbar")
        TelaMedico.setStatusBar(self.statusbar)
        self.tableWidget.setColumnWidth(0, 10)
        self.tableWidget.setColumnWidth(1, 150)
        self.tableWidget.setColumnWidth(2, 100)
        self.tableWidget.setColumnWidth(3, 100)
        self.retranslateUi(TelaMedico)
        QtCore.QMetaObject.connectSlotsByName(TelaMedico)
        TelaMedico.setWindowIcon(QtGui.QIcon("hospital.png"))
    def retranslateUi(self, TelaMedico):
        _translate = QtCore.QCoreApplication.translate
        TelaMedico.setWindowTitle(_translate("TelaMedico", "Sistema Hospitalar"))
        self.Label_titulo.setText(_translate("TelaMedico", "Informações do Médico"))
        self.pushButton_cadastrar.setText(_translate("TelaMedico", "Cadastrar"))
        self.pushButtor_visu.setText(_translate("TelaMedico", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaMedico", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaMedico", "Excluir"))
        self.label_nome.setText(_translate("TelaMedico", "Nome:"))
        self.label_crm.setText(_translate("TelaMedico", "CRM:"))
        self.label_especialidade.setText(_translate("TelaMedico", "Especialidade:"))
        self.label_id.setText(_translate("TelaMedico", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaMedico", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaMedico", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaMedico", "CRM"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaMedico", "Especialidade"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMedico = QtWidgets.QMainWindow()
    ui = Ui_TelaMedico()
    ui.setupUi(TelaMedico)
    TelaMedico.show()
    sys.exit(app.exec_())
