# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_setor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaSetor(object):
    def setupUi(self, TelaSetor):
        TelaSetor.setObjectName("TelaSetor")
        TelaSetor.setEnabled(True)
        TelaSetor.resize(570, 500)
        TelaSetor.setMinimumSize(QtCore.QSize(570, 500))
        TelaSetor.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        TelaSetor.setFont(font)
        TelaSetor.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaSetor.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaSetor)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(160, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(40, 110, 271, 20))
        self.lineEdit_nome.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setCursorPosition(0)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_salvar.setFlat(False)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(360, 220, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 220, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.lineEdit_id_setor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_setor.setEnabled(False)
        self.lineEdit_id_setor.setGeometry(QtCore.QRect(40, 220, 71, 20))
        self.lineEdit_id_setor.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_setor.setText("")
        self.lineEdit_id_setor.setObjectName("lineEdit_id_setor")
        self.label_id_setor = QtWidgets.QLabel(self.centralwidget)
        self.label_id_setor.setGeometry(QtCore.QRect(40, 200, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_setor.setFont(font)
        self.label_id_setor.setObjectName("label_id_setor")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 260, 491, 191))
        self.tableWidget.setStyleSheet("\n"
"color:#333;\n"
"background: transparent; \n"
"border-radius: 6px; \n"
"border: 1px solid #AAAAAA;  \n"
"ColumnWidth:1")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.lineEdit_descricao = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_descricao.setGeometry(QtCore.QRect(40, 170, 271, 20))
        self.lineEdit_descricao.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_descricao.setText("")
        self.lineEdit_descricao.setCursorPosition(0)
        self.lineEdit_descricao.setObjectName("lineEdit_descricao")
        self.label_descricao = QtWidgets.QLabel(self.centralwidget)
        self.label_descricao.setGeometry(QtCore.QRect(40, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_descricao.setFont(font)
        self.label_descricao.setObjectName("label_descricao")
        self.label_id_hospital = QtWidgets.QLabel(self.centralwidget)
        self.label_id_hospital.setGeometry(QtCore.QRect(340, 80, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_hospital.setFont(font)
        self.label_id_hospital.setObjectName("label_id_hospital")
        self.lineEdit_id_hospital = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_hospital.setGeometry(QtCore.QRect(340, 110, 71, 20))
        self.lineEdit_id_hospital.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_hospital.setText("")
        self.lineEdit_id_hospital.setCursorPosition(0)
        self.lineEdit_id_hospital.setObjectName("lineEdit_id_hospital")
        self.lineEdit_id_medico = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_medico.setGeometry(QtCore.QRect(440, 110, 71, 20))
        self.lineEdit_id_medico.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_medico.setText("")
        self.lineEdit_id_medico.setCursorPosition(0)
        self.lineEdit_id_medico.setObjectName("lineEdit_id_medico")
        self.lineEdit_id_enfermeiro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_enfermeiro.setGeometry(QtCore.QRect(340, 170, 71, 20))
        self.lineEdit_id_enfermeiro.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_enfermeiro.setText("")
        self.lineEdit_id_enfermeiro.setCursorPosition(0)
        self.lineEdit_id_enfermeiro.setObjectName("lineEdit_id_enfermeiro")
        self.lineEdit_id_paciente = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_paciente.setGeometry(QtCore.QRect(440, 170, 71, 20))
        self.lineEdit_id_paciente.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_paciente.setText("")
        self.lineEdit_id_paciente.setCursorPosition(0)
        self.lineEdit_id_paciente.setObjectName("lineEdit_id_paciente")
        self.label_id_medico = QtWidgets.QLabel(self.centralwidget)
        self.label_id_medico.setGeometry(QtCore.QRect(440, 80, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_medico.setFont(font)
        self.label_id_medico.setObjectName("label_id_medico")
        self.label_id_enfermeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_id_enfermeiro.setGeometry(QtCore.QRect(340, 140, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_enfermeiro.setFont(font)
        self.label_id_enfermeiro.setObjectName("label_id_enfermeiro")
        self.label_id_paciente = QtWidgets.QLabel(self.centralwidget)
        self.label_id_paciente.setGeometry(QtCore.QRect(440, 140, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_paciente.setFont(font)
        self.label_id_paciente.setObjectName("label_id_paciente")
        TelaSetor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaSetor)
        self.statusbar.setObjectName("statusbar")
        TelaSetor.setStatusBar(self.statusbar)

        self.retranslateUi(TelaSetor)
        QtCore.QMetaObject.connectSlotsByName(TelaSetor)

    def retranslateUi(self, TelaSetor):
        _translate = QtCore.QCoreApplication.translate
        TelaSetor.setWindowTitle(_translate("TelaSetor", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaSetor", "Setor"))
        self.pushButton_salvar.setText(_translate("TelaSetor", "Salvar"))
        self.pushButtor_visu.setText(_translate("TelaSetor", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaSetor", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaSetor", "Excluir"))
        self.label_nome.setText(_translate("TelaSetor", "Nome:"))
        self.label_id_setor.setText(_translate("TelaSetor", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaSetor", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaSetor", "Tipo de Atend.:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaSetor", "Data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaSetor", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaSetor", "Médico"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaSetor", "Enfermeiro"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaSetor", "Paciente"))
        self.label_descricao.setText(_translate("TelaSetor", "Descrição"))
        self.label_id_hospital.setText(_translate("TelaSetor", "ID Hospital:"))
        self.label_id_medico.setText(_translate("TelaSetor", "ID Medico:"))
        self.label_id_enfermeiro.setText(_translate("TelaSetor", "ID Enfermeiro:"))
        self.label_id_paciente.setText(_translate("TelaSetor", "ID Paciente:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaSetor = QtWidgets.QMainWindow()
    ui = Ui_TelaSetor()
    ui.setupUi(TelaSetor)
    TelaSetor.show()
    sys.exit(app.exec_())
