# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projeto.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaMenu(object):
    def setupUi(self, TelaMenu):
        TelaMenu.setObjectName("TelaMenu")
        TelaMenu.setEnabled(True)
        TelaMenu.resize(570, 500)
        TelaMenu.setMinimumSize(QtCore.QSize(570, 500))
        TelaMenu.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaMenu.setFont(font)
        TelaMenu.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaMenu.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(140, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(40, 110, 311, 20))
        self.lineEdit_nome.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_nome.setPlaceholderText("Digite o nome")
        self.lineEdit_nome.setCursorPosition(0)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(380, 110, 151, 20))
        self.lineEdit_cpf.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_cpf.setText("")
        self.lineEdit_cpf.setInputMask("000.000.000-00;_")
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.lineEdit_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data.setGeometry(QtCore.QRect(40, 170, 151, 21))
        self.lineEdit_data.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_data.setText("")
        self.lineEdit_data.setInputMask("00/00/0000;_")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.lineEdit_sexo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sexo.setGeometry(QtCore.QRect(210, 170, 41, 20))
        self.lineEdit_sexo.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_sexo.setPlaceholderText("sexo")
        self.lineEdit_sexo.setObjectName("lineEdit_sexo")
        self.lineEdit_telefone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telefone.setGeometry(QtCore.QRect(260, 170, 121, 20))
        self.lineEdit_telefone.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_telefone.setText("")
        self.lineEdit_telefone.setInputMask("(00) 0 0000-0000;_")
        self.lineEdit_telefone.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(390, 170, 141, 20))
        self.lineEdit_email.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_email.setPlaceholderText("Digite o email")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(450, 270, 75, 23))
        self.pushButton_cadastrar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_cadastrar.setFlat(False)
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(450, 300, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(450, 330, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 360, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.pushButton_atualizar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_atualizar.setGeometry(QtCore.QRect(450, 330, 75, 23))
        self.pushButton_atualizar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_atualizar.setFlat(True)
        self.pushButton_atualizar.setObjectName("pushButton_atualizar")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.label_cpf = QtWidgets.QLabel(self.centralwidget)
        self.label_cpf.setGeometry(QtCore.QRect(380, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_cpf.setFont(font)
        self.label_cpf.setObjectName("label_cpf")
        self.label_data = QtWidgets.QLabel(self.centralwidget)
        self.label_data.setGeometry(QtCore.QRect(40, 148, 120, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_data.setFont(font)
        self.label_data.setObjectName("label_data")
        self.label_sexo = QtWidgets.QLabel(self.centralwidget)
        self.label_sexo.setGeometry(QtCore.QRect(210, 150, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_sexo.setFont(font)
        self.label_sexo.setObjectName("label_sexo")
        self.label_telefone = QtWidgets.QLabel(self.centralwidget)
        self.label_telefone.setGeometry(QtCore.QRect(260, 148, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_telefone.setFont(font)
        self.label_telefone.setObjectName("label_telefone")
        self.label_email_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_email_2.setGeometry(QtCore.QRect(390, 150, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_email_2.setFont(font)
        self.label_email_2.setObjectName("label_email_2")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(False)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 230, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setPlaceholderText("Digite o ID")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(40, 210, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 270, 391, 181))
        self.tableWidget.setStyleSheet("""
QTableWidget {
    background-color: #F5F5F5; /* fundo geral */
    alternate-background-color: #E0FFFF; /* linhas alternadas */
}

QHeaderView::section {
    background-color: #504B4B; /* fundo do cabeçalho */
    color: white;
    font-weight: bold;
}
""")
       
        self.tableWidget.setColumnWidth(0, 10)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        TelaMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaMenu)
        self.statusbar.setObjectName("statusbar")
        TelaMenu.setStatusBar(self.statusbar)

        self.retranslateUi(TelaMenu)
        QtCore.QMetaObject.connectSlotsByName(TelaMenu)

    def retranslateUi(self, TelaMenu):
        _translate = QtCore.QCoreApplication.translate
        TelaMenu.setWindowTitle(_translate("TelaMenu", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaMenu", "Informações do Paciente"))
        self.pushButton_cadastrar.setText(_translate("TelaMenu", "Cadastrar"))
        self.pushButtor_visu.setText(_translate("TelaMenu", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaMenu", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaMenu", "Excluir"))
        self.pushButton_atualizar.setText(_translate("TelaMenu", "Atualizar"))
        self.label_nome.setText(_translate("TelaMenu", "Nome:"))
        self.label_cpf.setText(_translate("TelaMenu", "CPF:"))
        self.label_data.setText(_translate("TelaMenu", "Data de Nasc.:"))
        self.label_sexo.setText(_translate("TelaMenu", "Sexo:"))
        self.label_telefone.setText(_translate("TelaMenu", "Telefone:"))
        self.label_email_2.setText(_translate("TelaMenu", "Email:"))
        self.label_id.setText(_translate("TelaMenu", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaMenu", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaMenu", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaMenu", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaMenu", "Data de Nasc."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaMenu", "Sexo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaMenu", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaMenu", "Email"))
        self.tableWidget.setColumnWidth(0,10)
        self.tableWidget.setColumnWidth(6,100)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMenu = QtWidgets.QMainWindow()
    ui = Ui_TelaMenu()
    ui.setupUi(TelaMenu)
    TelaMenu.show()
    sys.exit(app.exec_())
