# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_internacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaInternacao(object):
    def setupUi(self, TelaInternacao):
        TelaInternacao.setObjectName("TelaInternacao")
        TelaInternacao.setEnabled(True)
        TelaInternacao.resize(570, 500)
        TelaInternacao.setMinimumSize(QtCore.QSize(570, 500))
        TelaInternacao.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        TelaInternacao.setFont(font)
        TelaInternacao.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaInternacao.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaInternacao)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(160, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_salvar.setFlat(False)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(360, 220, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 220, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(360, 80, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(False)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 220, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id_intern = QtWidgets.QLabel(self.centralwidget)
        self.label_id_intern.setGeometry(QtCore.QRect(40, 200, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_intern.setFont(font)
        self.label_id_intern.setObjectName("label_id_intern")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 260, 491, 191))
        self.tableWidget.setStyleSheet("\n"
"color:#333;\n"
"background: transparent; \n"
"border-radius: 6px; \n"
"border: 1px solid #AAAAAA;  \n"
"ColumnWidth:1")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.comboBox_status = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_status.setGeometry(QtCore.QRect(360, 110, 151, 21))
        self.comboBox_status.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      \n"
"\n"
"")
        self.comboBox_status.setObjectName("comboBox_status")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.label_id_pacien = QtWidgets.QLabel(self.centralwidget)
        self.label_id_pacien.setGeometry(QtCore.QRect(40, 150, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_pacien.setFont(font)
        self.label_id_pacien.setObjectName("label_id_pacien")
        self.lineEdit_id_paciente = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_paciente.setEnabled(False)
        self.lineEdit_id_paciente.setGeometry(QtCore.QRect(40, 170, 71, 20))
        self.lineEdit_id_paciente.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_paciente.setText("")
        self.lineEdit_id_paciente.setObjectName("lineEdit_id_paciente")
        self.label_entrada = QtWidgets.QLabel(self.centralwidget)
        self.label_entrada.setGeometry(QtCore.QRect(40, 90, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_entrada.setFont(font)
        self.label_entrada.setObjectName("label_entrada")
        self.label_saida = QtWidgets.QLabel(self.centralwidget)
        self.label_saida.setGeometry(QtCore.QRect(180, 90, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_saida.setFont(font)
        self.label_saida.setObjectName("label_saida")
        self.label_id_leito = QtWidgets.QLabel(self.centralwidget)
        self.label_id_leito.setGeometry(QtCore.QRect(160, 150, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_leito.setFont(font)
        self.label_id_leito.setObjectName("label_id_leito")
        self.lineEdit_id_leito = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_leito.setEnabled(False)
        self.lineEdit_id_leito.setGeometry(QtCore.QRect(160, 170, 71, 20))
        self.lineEdit_id_leito.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_leito.setText("")
        self.lineEdit_id_leito.setObjectName("lineEdit_id_leito")
        self.dateTime_entr = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTime_entr.setGeometry(QtCore.QRect(40, 110, 121, 25))
        self.dateTime_entr.setObjectName("dateTime_entr")
        self.dateTime_saida = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTime_saida.setGeometry(QtCore.QRect(180, 110, 121, 25))
        self.dateTime_saida.setObjectName("dateTime_saida")
        TelaInternacao.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaInternacao)
        self.statusbar.setObjectName("statusbar")
        TelaInternacao.setStatusBar(self.statusbar)

        self.retranslateUi(TelaInternacao)
        QtCore.QMetaObject.connectSlotsByName(TelaInternacao)

    def retranslateUi(self, TelaInternacao):
        _translate = QtCore.QCoreApplication.translate
        TelaInternacao.setWindowTitle(_translate("TelaInternacao", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaInternacao", "Internação"))
        self.pushButton_salvar.setText(_translate("TelaInternacao", "Salvar"))
        self.pushButtor_visu.setText(_translate("TelaInternacao", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaInternacao", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaInternacao", "Excluir"))
        self.label_status.setText(_translate("TelaInternacao", "Status"))
        self.label_id_intern.setText(_translate("TelaInternacao", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaInternacao", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaInternacao", "Tipo de Atend.:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaInternacao", "Data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaInternacao", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaInternacao", "Médico"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaInternacao", "Enfermeiro"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaInternacao", "Paciente"))
        self.comboBox_status.setItemText(0, _translate("TelaInternacao", "Aberto"))
        self.comboBox_status.setItemText(1, _translate("TelaInternacao", "Concluído"))
        self.comboBox_status.setItemText(2, _translate("TelaInternacao", "Cancelado"))
        self.label_id_pacien.setText(_translate("TelaInternacao", "ID Paciente:"))
        self.label_entrada.setText(_translate("TelaInternacao", "Entrada: "))
        self.label_saida.setText(_translate("TelaInternacao", "Saida: "))
        self.label_id_leito.setText(_translate("TelaInternacao", "ID Leito:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaInternacao = QtWidgets.QMainWindow()
    ui = Ui_TelaInternacao()
    ui.setupUi(TelaInternacao)
    TelaInternacao.show()
    sys.exit(app.exec_())
