# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_cidade.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaCidade(object):
    def setupUi(self, TelaCidade):
        TelaCidade.setObjectName("TelaCidade")
        TelaCidade.setEnabled(True)
        TelaCidade.resize(570, 500)
        TelaCidade.setMinimumSize(QtCore.QSize(570, 500))
        TelaCidade.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        TelaCidade.setFont(font)
        TelaCidade.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaCidade.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaCidade)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(170, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(40, 110, 261, 20))
        self.lineEdit_nome.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setCursorPosition(0)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_salvar.setFlat(False)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(360, 220, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 220, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(False)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 170, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id_cidade = QtWidgets.QLabel(self.centralwidget)
        self.label_id_cidade.setGeometry(QtCore.QRect(40, 150, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_cidade.setFont(font)
        self.label_id_cidade.setObjectName("label_id_cidade")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 260, 491, 191))
        self.tableWidget.setStyleSheet("\n"
"color:#333;\n"
"background: transparent; \n"
"border-radius: 6px; \n"
"border: 1px solid #AAAAAA;  \n"
"ColumnWidth:1")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.label_id_estado = QtWidgets.QLabel(self.centralwidget)
        self.label_id_estado.setGeometry(QtCore.QRect(330, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_estado.setFont(font)
        self.label_id_estado.setObjectName("label_id_estado")
        self.label_id_hospital = QtWidgets.QLabel(self.centralwidget)
        self.label_id_hospital.setGeometry(QtCore.QRect(420, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id_hospital.setFont(font)
        self.label_id_hospital.setObjectName("label_id_hospital")
        self.lineEdit_id_estado = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_estado.setEnabled(False)
        self.lineEdit_id_estado.setGeometry(QtCore.QRect(330, 110, 71, 20))
        self.lineEdit_id_estado.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_estado.setText("")
        self.lineEdit_id_estado.setObjectName("lineEdit_id_estado")
        self.lineEdit_id_hospital = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_hospital.setEnabled(False)
        self.lineEdit_id_hospital.setGeometry(QtCore.QRect(420, 110, 71, 20))
        self.lineEdit_id_hospital.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_hospital.setText("")
        self.lineEdit_id_hospital.setObjectName("lineEdit_id_hospital")
        TelaCidade.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaCidade)
        self.statusbar.setObjectName("statusbar")
        TelaCidade.setStatusBar(self.statusbar)

        self.retranslateUi(TelaCidade)
        QtCore.QMetaObject.connectSlotsByName(TelaCidade)

    def retranslateUi(self, TelaCidade):
        _translate = QtCore.QCoreApplication.translate
        TelaCidade.setWindowTitle(_translate("TelaCidade", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaCidade", "Cidade"))
        self.pushButton_salvar.setText(_translate("TelaCidade", "Salvar"))
        self.pushButtor_visu.setText(_translate("TelaCidade", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaCidade", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaCidade", "Excluir"))
        self.label_nome.setText(_translate("TelaCidade", "Nome:"))
        self.label_id_cidade.setText(_translate("TelaCidade", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaCidade", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaCidade", "Tipo de Atend.:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaCidade", "Data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaCidade", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaCidade", "Médico"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaCidade", "Enfermeiro"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaCidade", "Paciente"))
        self.label_id_estado.setText(_translate("TelaCidade", "ID Estado:"))
        self.label_id_hospital.setText(_translate("TelaCidade", "ID Hospital:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaCidade = QtWidgets.QMainWindow()
    ui = Ui_TelaCidade()
    ui.setupUi(TelaCidade)
    TelaCidade.show()
    sys.exit(app.exec_())
