# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaMenu2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaMenu(object):
    def setupUi(self, TelaMenu):
        TelaMenu.setObjectName("TelaMenu")
        TelaMenu.setEnabled(True)
        TelaMenu.resize(570, 500)
        TelaMenu.setMinimumSize(QtCore.QSize(570, 500))
        TelaMenu.setMaximumSize(QtCore.QSize(570, 500))

        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaMenu.setFont(font)

        TelaMenu.setStyleSheet("QMainWindow {\n"
                               "    background-color:#F1F1F1;\n"
                               "}")

        TelaMenu.setIconSize(QtCore.QSize(24, 24))

        self.centralwidget = QtWidgets.QWidget(TelaMenu)
        self.centralwidget.setObjectName("centralwidget")

        # =====================
        # LABEL TÍTULO
        # =====================
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(190, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")

        # =====================
        # BOTÕES LADO ESQUERDO
        # =====================

        self.pushButton_paciente = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_paciente.setGeometry(QtCore.QRect(50, 140, 221, 31))
        self.pushButton_paciente.setStyleSheet(self._buttonStyle())
        self.pushButton_paciente.setObjectName("pushButton_paciente")

        self.pushButton_enfermeiro = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enfermeiro.setGeometry(QtCore.QRect(50, 180, 221, 31))
        self.pushButton_enfermeiro.setStyleSheet(self._buttonStyle())
        self.pushButton_enfermeiro.setObjectName("pushButton_enfermeiro")

        self.pushButton_medico = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_medico.setGeometry(QtCore.QRect(50, 220, 221, 31))
        self.pushButton_medico.setStyleSheet(self._buttonStyle())
        self.pushButton_medico.setObjectName("pushButton_medico")

        self.pushButton_arquivo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arquivo.setGeometry(QtCore.QRect(50, 260, 221, 31))
        self.pushButton_arquivo.setStyleSheet(self._buttonStyle())
        self.pushButton_arquivo.setObjectName("pushButton_arquivo")

        # =====================
        # BOTÕES LADO DIREITO
        # =====================

        self.pushButton_atendimento = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_atendimento.setGeometry(QtCore.QRect(300, 140, 221, 31))
        self.pushButton_atendimento.setStyleSheet(self._buttonStyle())
        self.pushButton_atendimento.setObjectName("pushButton_atendimento")

        self.pushButton_leito = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_leito.setGeometry(QtCore.QRect(300, 180, 221, 31))
        self.pushButton_leito.setStyleSheet(self._buttonStyle())
        self.pushButton_leito.setObjectName("pushButton_leito")

        self.pushButton_setor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setor.setGeometry(QtCore.QRect(300, 220, 221, 31))
        self.pushButton_setor.setStyleSheet(self._buttonStyle())
        self.pushButton_setor.setObjectName("pushButton_setor")

        self.pushButton_turno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_turno.setGeometry(QtCore.QRect(300, 260, 221, 31))
        self.pushButton_turno.setStyleSheet(self._buttonStyle())
        self.pushButton_turno.setObjectName("pushButton_turno")

        # =====================
        # BOTÕES ADICIONAIS DO .UI
        # =====================

        self.pushButton_cidade = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cidade.setGeometry(QtCore.QRect(170, 140, 221, 31))
        self.pushButton_cidade.setStyleSheet(self._buttonStyle())
        self.pushButton_cidade.setObjectName("pushButton_cidade")

        self.pushButton_internacoes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_internacoes.setGeometry(QtCore.QRect(170, 180, 221, 31))
        self.pushButton_internacoes.setStyleSheet(self._buttonStyle())
        self.pushButton_internacoes.setObjectName("pushButton_internacoes")

        self.pushButton_hospital = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hospital.setGeometry(QtCore.QRect(170, 260, 221, 31))
        self.pushButton_hospital.setStyleSheet(self._buttonStyle())
        self.pushButton_hospital.setObjectName("pushButton_hospital")

        self.pushButton_estado = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_estado.setGeometry(QtCore.QRect(170, 220, 221, 31))
        self.pushButton_estado.setStyleSheet(self._buttonStyle())
        self.pushButton_estado.setObjectName("pushButton_estado")

        # =====================
        # NAVEGAÇÃO
        # =====================

        self.pushButton_proxPag = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_proxPag.setGeometry(QtCore.QRect(420, 400, 101, 31))
        self.pushButton_proxPag.setStyleSheet(self._buttonStyle())
        self.pushButton_proxPag.setObjectName("pushButton_proxPag")

        self.pushButton_pagAnterior = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pagAnterior.setGeometry(QtCore.QRect(45, 400, 101, 31))
        self.pushButton_pagAnterior.setStyleSheet(self._buttonStyle())
        self.pushButton_pagAnterior.setObjectName("pushButton_pagAnterior")
        self.pushButton_pagAnterior.hide()
        self.pushButton_cidade.hide()
        self.pushButton_estado.hide()
        self.pushButton_internacoes.hide()
        self.pushButton_hospital.hide()
        TelaMenu.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(TelaMenu)
        self.statusbar.setObjectName("statusbar")
        TelaMenu.setStatusBar(self.statusbar)

        self.retranslateUi(TelaMenu)
        QtCore.QMetaObject.connectSlotsByName(TelaMenu)

    # =============================
    # ESTILO DOS BOTÕES (FUNÇÃO)
    # =============================
    def _buttonStyle(self):
        return ("QPushButton {\n"
                "background: #504B4B;\n"
                "color: #FFFFFF;\n"
                "border-radius: 4px;\n"
                "padding: 5px;\n"
                "}\n"
                "QPushButton:hover {\n"
                "background-color: #5599ff;\n"
                "}\n"
                "QPushButton:pressed {\n"
                "background-color: #2e5ea2;\n"
                "padding-top: 8px;\n"
                "padding-bottom: 4px;\n"
                "}")

    # =============================
    # TEXTOS DO UI
    # =============================
    def retranslateUi(self, TelaMenu):
        _translate = QtCore.QCoreApplication.translate

        TelaMenu.setWindowTitle(_translate("TelaMenu", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaMenu", "Menu Hospital"))

        self.pushButton_medico.setText(_translate("TelaMenu", "Médico"))
        self.pushButton_paciente.setText(_translate("TelaMenu", "Paciente"))
        self.pushButton_enfermeiro.setText(_translate("TelaMenu", "Enfermeiro"))
        self.pushButton_arquivo.setText(_translate("TelaMenu", "Arquivo"))
        self.pushButton_leito.setText(_translate("TelaMenu", "Leito"))
        self.pushButton_atendimento.setText(_translate("TelaMenu", "Atendimento"))
        self.pushButton_setor.setText(_translate("TelaMenu", "Setor"))
        self.pushButton_turno.setText(_translate("TelaMenu", "Turno"))

        self.pushButton_cidade.setText(_translate("TelaMenu", "Cidade"))
        self.pushButton_internacoes.setText(_translate("TelaMenu", "Internações"))
        self.pushButton_estado.setText(_translate("TelaMenu", "Estado"))
        self.pushButton_hospital.setText(_translate("TelaMenu", "Hospital"))
        self.pushButton_proxPag.setText(_translate("TelaMenu", "Próxima página"))
        self.pushButton_pagAnterior.setText(_translate("TelaMenu", "Página anterior"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMenu = QtWidgets.QMainWindow()
    ui = Ui_TelaMenu()
    ui.setupUi(TelaMenu)
    TelaMenu.show()
    sys.exit(app.exec_())
