# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_administrador.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaAdministrador(object):
    def setupUi(self, TelaAdministrador):
        TelaAdministrador.setObjectName("TelaAdministrador")
        TelaAdministrador.setEnabled(True)
        TelaAdministrador.resize(570, 500)
        TelaAdministrador.setMinimumSize(QtCore.QSize(570, 500))
        TelaAdministrador.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        TelaAdministrador.setFont(font)
        TelaAdministrador.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaAdministrador.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaAdministrador)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(170, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(40, 100, 381, 20))
        self.lineEdit_nome.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setCursorPosition(0)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_salvar.setFlat(False)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(360, 220, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 220, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(False)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 200, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(40, 180, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 260, 491, 191))
        self.tableWidget.setStyleSheet("\n"
"color:#333;\n"
"background: transparent; \n"
"border-radius: 6px; \n"
"border: 1px solid #AAAAAA;  \n"
"ColumnWidth:1")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(40, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(40, 150, 321, 20))
        self.lineEdit_email.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setCursorPosition(0)
        self.lineEdit_email.setObjectName("lineEdit_email")
        TelaAdministrador.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaAdministrador)
        self.statusbar.setObjectName("statusbar")
        TelaAdministrador.setStatusBar(self.statusbar)

        self.retranslateUi(TelaAdministrador)
        QtCore.QMetaObject.connectSlotsByName(TelaAdministrador)

    def retranslateUi(self, TelaAdministrador):
        _translate = QtCore.QCoreApplication.translate
        TelaAdministrador.setWindowTitle(_translate("TelaAdministrador", "MainWindow"))
        self.Label_titulo.setText(_translate("TelaAdministrador", "Administrador"))
        self.pushButton_salvar.setText(_translate("TelaAdministrador", "Salvar"))
        self.pushButtor_visu.setText(_translate("TelaAdministrador", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaAdministrador", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaAdministrador", "Excluir"))
        self.label_nome.setText(_translate("TelaAdministrador", "Nome:"))
        self.label_id.setText(_translate("TelaAdministrador", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaAdministrador", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaAdministrador", "Tipo de Atend.:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaAdministrador", "Data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaAdministrador", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaAdministrador", "Médico"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaAdministrador", "Enfermeiro"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaAdministrador", "Paciente"))
        self.label_email.setText(_translate("TelaAdministrador", "Email:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaAdministrador = QtWidgets.QMainWindow()
    ui = Ui_TelaAdministrador()
    ui.setupUi(TelaAdministrador)
    TelaAdministrador.show()
    sys.exit(app.exec_())
