# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_hospital.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaHospital(object):
    def setupUi(self, TelaHospital):
        TelaHospital.setObjectName("TelaHospital")
        TelaHospital.setEnabled(True)
        TelaHospital.resize(570, 500)
        TelaHospital.setMinimumSize(QtCore.QSize(570, 500))
        TelaHospital.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaHospital.setFont(font)
        TelaHospital.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaHospital.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaHospital)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(130, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(40, 110, 311, 20))
        self.lineEdit_nome.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setCursorPosition(0)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_cnpj = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cnpj.setGeometry(QtCore.QRect(380, 110, 151, 20))
        self.lineEdit_cnpj.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_cnpj.setInputMask("00.000.000/000-00;_")
        self.lineEdit_cnpj.setText("")
        self.lineEdit_cnpj.setObjectName("lineEdit_cnpj")
        self.lineEdit_endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_endereco.setGeometry(QtCore.QRect(40, 170, 151, 21))
        self.lineEdit_endereco.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_endereco.setText("")
        self.lineEdit_endereco.setObjectName("lineEdit_endereco")
        self.lineEdit_telefone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telefone.setGeometry(QtCore.QRect(210, 170, 121, 20))
        self.lineEdit_telefone.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_telefone.setText("")
        self.lineEdit_telefone.setInputMask("(00) 0 0000-0000;_")
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(340, 170, 191, 20))
        self.lineEdit_email.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(210, 230, 75, 23))
        self.pushButton_cadastrar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_cadastrar.setFlat(False)
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.pushButton_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_visu.setGeometry(QtCore.QRect(290, 230, 75, 23))
        self.pushButton_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_visu.setFlat(False)
        self.pushButton_visu.setObjectName("pushButton_visu")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(370, 230, 75, 23))
        self.pushButton_editar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_editar.setFlat(False)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excluir.setGeometry(QtCore.QRect(450, 230, 75, 23))
        self.pushButton_excluir.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_excluir.setFlat(False)
        self.pushButton_excluir.setObjectName("pushButton_excluir")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.label_cnpj = QtWidgets.QLabel(self.centralwidget)
        self.label_cnpj.setGeometry(QtCore.QRect(380, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_cnpj.setFont(font)
        self.label_cnpj.setObjectName("label_cnpj")
        self.label_endereco = QtWidgets.QLabel(self.centralwidget)
        self.label_endereco.setGeometry(QtCore.QRect(40, 150, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_endereco.setFont(font)
        self.label_endereco.setObjectName("label_endereco")
        self.label_telefone = QtWidgets.QLabel(self.centralwidget)
        self.label_telefone.setGeometry(QtCore.QRect(210, 148, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_telefone.setFont(font)
        self.label_telefone.setObjectName("label_telefone")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(340, 150, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(True)
        self.lineEdit_id.setGeometry(QtCore.QRect(110, 230, 51, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id_hospital = QtWidgets.QLabel(self.centralwidget)
        self.label_id_hospital.setGeometry(QtCore.QRect(110, 206, 21, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_hospital.setFont(font)
        self.label_id_hospital.setObjectName("label_id_hospital")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 290, 491, 181))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #E0FFFF;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #504B4B;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.lineEdit_id_admin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id_admin.setGeometry(QtCore.QRect(40, 230, 51, 20))
        self.lineEdit_id_admin.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id_admin.setText("")
        self.lineEdit_id_admin.setObjectName("lineEdit_id_admin")
        self.label_Id_admin = QtWidgets.QLabel(self.centralwidget)
        self.label_Id_admin.setGeometry(QtCore.QRect(40, 210, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Id_admin.setFont(font)
        self.label_Id_admin.setObjectName("label_Id_admin")
        TelaHospital.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaHospital)
        self.statusbar.setObjectName("statusbar")
        TelaHospital.setStatusBar(self.statusbar)
        TelaHospital.setWindowIcon(QtGui.QIcon("hospital.png"))
        self.retranslateUi(TelaHospital)
        QtCore.QMetaObject.connectSlotsByName(TelaHospital)

    def retranslateUi(self, TelaHospital):
        _translate = QtCore.QCoreApplication.translate
        TelaHospital.setWindowTitle(_translate("TelaHospital", "Sistema Hospitalar"))
        self.Label_titulo.setText(_translate("TelaHospital", "Informações do Hospital"))
        self.pushButton_cadastrar.setText(_translate("TelaHospital", "Cadastrar"))
        self.pushButton_visu.setText(_translate("TelaHospital", "Visualizar"))
        self.pushButton_editar.setText(_translate("TelaHospital", "Editar"))
        self.pushButton_excluir.setText(_translate("TelaHospital", "Excluir"))
        self.label_nome.setText(_translate("TelaHospital", "Nome:"))
        self.label_cnpj.setText(_translate("TelaHospital", "CNPJ:"))
        self.label_endereco.setText(_translate("TelaHospital", "Endereço:"))
        self.label_telefone.setText(_translate("TelaHospital", "Telefone:"))
        self.label_email.setText(_translate("TelaHospital", "Email:"))
        self.label_id_hospital.setText(_translate("TelaHospital", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaHospital", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaHospital", "Nome Hospital"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaHospital", "CNPJ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaHospital", "Endereço"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaHospital", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaHospital", "Email"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaHospital", "ID Admin.:"))
        self.label_Id_admin.setText(_translate("TelaHospital", "ID Adm.:"))
        self.tableWidget.setColumnWidth(0, 10)
        self.tableWidget.setColumnWidth(1, 100)
        self.tableWidget.setColumnWidth(2,100)
        self.tableWidget.setColumnWidth(6, 100)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaHospital = QtWidgets.QMainWindow()
    ui = Ui_TelaHospital()
    ui.setupUi(TelaHospital)
    TelaHospital.show()
    sys.exit(app.exec_())
