# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_arquivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaArquivo(object):
    def setupUi(self, TelaArquivo):
        TelaArquivo.setObjectName("TelaArquivo")
        TelaArquivo.setEnabled(True)
        TelaArquivo.resize(570, 500)
        TelaArquivo.setMinimumSize(QtCore.QSize(570, 500))
        TelaArquivo.setMaximumSize(QtCore.QSize(570, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        TelaArquivo.setFont(font)
        TelaArquivo.setStyleSheet("QMainWindow {\n"
"    background-color:#F1F1F1\n"
";  /* cor de fundo da janela */\n"
"}")
        TelaArquivo.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(TelaArquivo)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(230, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setObjectName("Label_titulo")
        self.lineEdit_arquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_arquivo.setGeometry(QtCore.QRect(40, 95, 491, 20))
        self.lineEdit_arquivo.setStyleSheet("color: #333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_arquivo.setText("")
        self.lineEdit_arquivo.setCursorPosition(0)
        self.lineEdit_arquivo.setObjectName("lineEdit_arquivo")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(40, 230, 75, 23))
        self.pushButton_cadastrar.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButton_cadastrar.setFlat(False)
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.pushButtor_visu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.pushButtor_visu.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu.setFlat(False)
        self.pushButtor_visu.setObjectName("pushButtor_visu")
        self.label_arquivo = QtWidgets.QLabel(self.centralwidget)
        self.label_arquivo.setGeometry(QtCore.QRect(40, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_arquivo.setFont(font)
        self.label_arquivo.setObjectName("label_arquivo")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setEnabled(True)
        self.lineEdit_id.setGeometry(QtCore.QRect(40, 180, 71, 20))
        self.lineEdit_id.setStyleSheet("color:#333;\n"
"background: transparent; \n"
"border-radius: 4px; \n"
"border: 1px solid #AAAAAA;  \n"
"padding-left: 4px;      ")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(40, 160, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 270, 491, 181))
        self.tableWidget.setStyleSheet(
            "QTableWidget { background-color: #F5F5F5; alternate-background-color: #E0FFFF; }\n"
            "QHeaderView::section { background-color: #504B4B; color: white; font-weight: bold; }"
        )
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(66)
        self.pushButtor_visu_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtor_visu_2.setGeometry(QtCore.QRect(40, 120, 75, 23))
        self.pushButtor_visu_2.setStyleSheet("QPushButton {\n"
"background: #504B4B;          /* fundo transparente */\n"
"color: #FFFFFF;                   /* cor do texto */       \n"
"border-radius: 4px;              /* arredondamento */\n"
"padding: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5599ff;    /* cor quando o mouse passa por cima */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea2;    /* cor quando o botão é clicado */\n"
"    padding-top: 8px;             /* leve deslocamento pra baixo */\n"
"    padding-bottom: 4px;\n"
"}")
        self.pushButtor_visu_2.setFlat(False)
        self.pushButtor_visu_2.setObjectName("pushButtor_visu_2")
        TelaArquivo.setCentralWidget(self.centralwidget)
        self.tableWidget.setColumnWidth(0, 55)
        self.tableWidget.setColumnWidth(1, 218)
        self.tableWidget.setColumnWidth(2, 218)
        self.statusbar = QtWidgets.QStatusBar(TelaArquivo)
        self.statusbar.setObjectName("statusbar")
        TelaArquivo.setStatusBar(self.statusbar)
        TelaArquivo.setWindowIcon(QtGui.QIcon("arquivo.png"))
        
        self.retranslateUi(TelaArquivo)
        QtCore.QMetaObject.connectSlotsByName(TelaArquivo)

    def retranslateUi(self, TelaArquivo):
        _translate = QtCore.QCoreApplication.translate
        TelaArquivo.setWindowTitle(_translate("TelaArquivo", "Sistema de arquivo"))
        self.Label_titulo.setText(_translate("TelaArquivo", "Arquivo"))
        self.pushButton_cadastrar.setText(_translate("TelaArquivo", "Inserir"))
        self.pushButtor_visu.setText(_translate("TelaArquivo", "Visualizar"))
        self.pushButtor_visu_2.setText(_translate("TelaArquivo", "Buscar"))
        self.label_arquivo.setText(_translate("TelaArquivo", "Arquivo:"))
        self.label_id.setText(_translate("TelaArquivo", "ID:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaArquivo", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaArquivo", "Nome Arquivo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaArquivo", "Dados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaArquivo = QtWidgets.QMainWindow()
    ui = Ui_TelaArquivo()
    ui.setupUi(TelaArquivo)
    TelaArquivo.show()
    sys.exit(app.exec_())
